### ISSUE TITLE
settingsPath is not defined

### ISSUE THREAD

**Issue by psenechal** [DecentCMS/DecentCMS#3]
Hi Bertrand,

I seem to be having an issue similar to the previous two issues, but a slightly different error message and the fix didn't work for me. When starting the server, I'm getting the following error:

Error at boot ReferenceError: settingsPath is not defined

It's referencing shell.js in the Multi-tenancy module's lib folder

I didn't encounter any errors during the install and my versions are all within the guidelines you specified in the install docs. I made sure to run npm install in the multi-tenancy folder as well.

Any ideas on how to get around this? Thanks!

**Comment by bleroy** [comment]
Do you have a full stack trace?

**Comment by bleroy** [comment]
Also, do you have a site in the sites folder, with a settings file?

**Comment by psenechal** [comment]
yes...sorry

Error at boot ReferenceError: settingsPath is not defined
    at /Users/philipsenechal/Documents/DecentCMS/modules/core/multi-tenancy/lib/shell.js:116:59
    at Array.forEach (native)
    at Function.Shell.discover (/Users/philipsenechal/Documents/DecentCMS/modules/core/multi-tenancy/lib/shell.js:108:13)
    at Domain.<anonymous> (/Users/philipsenechal/Documents/DecentCMS/server.js:37:11)
    at Domain.run (domain.js:197:16)
    at Object.<anonymous> (/Users/philipsenechal/Documents/DecentCMS/server.js:32:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by psenechal** [comment]
yes to the other question as well. I cloned the DecentCMS.org repository and put it in sites/default off the root folder (renamed the cloned folder to default after I cloned it)

**Comment by bleroy** [comment]
Is there anything else in that sites folder? Can you describe what's in there?

**Comment by bleroy** [comment]
I pushed a small change that should at least give us a better idea of what's wrong. Can you try again with it?

**Comment by psenechal** [comment]
new stack trace:

Philips-MacBook-Air:DecentCMS philipsenechal$ node server
Error at boot Error: Failed to load site settings for .DS_Store
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Shell.load (/Users/philipsenechal/Documents/DecentCMS/modules/core/multi-tenancy/lib/shell.js:85:18)
    at /Users/philipsenechal/Documents/DecentCMS/modules/core/multi-tenancy/lib/shell.js:111:25
    at Array.forEach (native)
    at Function.Shell.discover (/Users/philipsenechal/Documents/DecentCMS/modules/core/multi-tenancy/lib/shell.js:108:13)
    at Domain.<anonymous> (/Users/philipsenechal/Documents/DecentCMS/server.js:37:11)
    at Domain.run (domain.js:197:16)

oh crap...is that a stupid hidden OS X file in there causing an issue?

**Comment by bleroy** [comment]
Yes, but I should be resilient to that.

**Comment by bleroy** [comment]
Try with this new change. It should fix that immediate issue, but there may be others like that. Good that you're testing on MacOS.

**Comment by psenechal** [comment]
Looks like that resolved the issue...THANKS!

I'll keep you up to date on anything I encounter that may be MacOS related =)

**Comment by bleroy** [comment]
Thanks!
