### ISSUE TITLE
Error: "Server choaked on this request"

### ISSUE THREAD

**Issue by HansS** [DecentCMS/DecentCMS#4]
I managed to install descentcms and the sample app (descentconsulting under /sites/default) but got an error when i started with node server.js:
C:\Users\Hans\web\cms\descentcms-1>node server
verbose: Added static file route. path=C:\Users\Hans\web\cms\descentcms-1\themes\default\css
verbose: Added static file route. path=C:\Users\Hans\web\cms\descentcms-1\themes\default\js
verbose: Added static file route. path=C:\Users\Hans\web\cms\descentcms-1\themes\default\img
verbose: Added static file route. path=C:\Users\Hans\web\cms\descentcms-1\themes\default\fonts
verbose: Added media static file route. path=C:\Users\Hans\web\cms\descentcms-1\sites\default\media
verbose: Added static favicon.ico route. path=C:\Users\Hans\web\cms\descentcms-1\favicon.ico
verbose: Registered Express middleware.
Unrecoverable error Error: Cannot find module 'htmlencode'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at new RenderStream (C:\Users\Hans\web\cms\descentcms-1\modules\core\ui\services\render-stream.js:16:14)
    at construct (C:\Users\Hans\web\cms\descentcms-1\modules\core\multi-tenancy\node_modules\decent-core-dependency-injection\lib\scope.js:26:20)
    at IncomingMessage.require (C:\Users\Hans\web\cms\descentcms-1\modules\core\multi-tenancy\node_modules\decent-core-dependency-injection\lib\scope.js:196:12)
    at ContentRenderer.render (C:\Users\Hans\web\cms\descentcms-1\modules\core\content\services\content-renderer.js:80:28)
    at C:\Users\Hans\web\cms\descentcms-1\modules\core\multi-tenancy\node_modules\async\lib\async.js:1080:20
    at iterate (C:\Users\Hans\web\cms\descentcms-1\modules\core\multi-tenancy\node_modules\async\lib\async.js:149:13)

**Comment by bleroy** [comment]
Thanks for reporting this. It seems like something went wrong when you did the `grunt install` step of the installation procedure. Can you open a command-line on `/modules/core/ui` and `npm install` from there? As a result, you should have `htmlencode` under `/modules/core/ui/node_modules`.

**Comment by HansS** [comment]
The htmlencode module is there but i still get the error when i start the server (node server.js):

C:\Users\Hans\web\cms\descentcms-1>node server
verbose: Added static file route. path=C:\Users\Hans\web\cms\descentcms-1\themes\default\css
verbose: Added static file route. path=C:\Users\Hans\web\cms\descentcms-1\themes\default\js
verbose: Added static file route. path=C:\Users\Hans\web\cms\descentcms-1\themes\default\img
verbose: Added static file route. path=C:\Users\Hans\web\cms\descentcms-1\themes\default\fonts
verbose: Added media static file route. path=C:\Users\Hans\web\cms\descentcms-1\sites\default\media
verbose: Added static favicon.ico route. path=C:\Users\Hans\web\cms\descentcms-1\favicon.ico
verbose: Registered Express middleware.
Unrecoverable error Error: Cannot find module 'htmlencode'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Hans\web\cms\descentcms-1\modules\core\parts\views\text.js:3:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by bleroy** [comment]
I'm sorry you're experiencing those difficulties. To be sure, I double-checked the installation procedure on a vanilla system, and couldn't reproduce the problem.

OK, so that second stack trace is different. Now it seems like the dependency is missing from the parts module. It seems like your `grunt install` went really wrong.

Try another npm install from `/core/parts`.

**Comment by HansS** [comment]
Hallo Bertrand,
sorry but i will till your cms is more stable.To my opinion the initial installation is much to havy. It should be that easy to install like an express application.I only keep on trying if it is important for you, for me it is not.
Kind regardsHans

Date: Wed, 18 Mar 2015 18:28:35 -0700

**Comment by bleroy** [comment]
No kidding ;) And I thought I had put enough big red flashing lights everywhere to make it clear that this is still highly experimental... If it's not important to you, let's forget about this. I'll close. Thanks for trying it.
